spring.config.import=optional:file:.env[.properties]

spring.application.name=telegram-pms-bot

## H2 database configuration (commented out for production use)
# spring.datasource.url=jdbc:h2:mem:telegram_pms_dev
# spring.datasource.driver-class-name=org.h2.Driver

## PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/telegram_pms_bot
spring.datasource.username=postgres
spring.datasource.password=123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.admin.chat-id=${TELEGRAM_ADMIN_CHAT_ID}
telegram.api.base-url=https://api.telegram.org
telegram.polling.enabled=true
telegram.polling.interval=5000

